menu:
    Home: /
    Archive: /archives
    About: /about

menu_icon:
    Home: icon-home
    Archive: icon-archive
    About: icon-user

excerpt_link: Read More
archive_yearly: true

# widgets:
#     - category

twitter_url: http://twitter.com/johnnyclem
facebook_url: http://facebook.com/johnnyclem
github_url: https://github.com/johnnyclem

# google_analytics_track_id: UA-43460643-1
# google_analytics_website: http://minddiaper.com

google_code_prettify: true
google_code_prettify_theme: prettify_raytaylorism
rss:
