menu:
  Home: /
  Archives: /archives

widgets: 
# - search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username: twitter
  show_replies: false
  tweet_count: 5

facebook: your facebook url
github: github
email: email
about: "Something about you here"
photo: http://www.techinasia.com/techinasia/wp-content/uploads/2009/11/facebook-avatar.png

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: